version: '3.9'


services:
  producer:
    image: ${DOCKER_REGISTRY-}producer
    build:
      context: .
      dockerfile: Producer/Dockerfile
    depends_on: 
      - rabbitmq


  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    depends_on: 
      - rabbitmq


  rabbitmq:
    image: rabbitmq:3.13-rc-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - C:\rmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
